### ISSUE TITLE
Potentially unused layers | Are the layers `self.proj1,self. proj2` ever called?

### ISSUE THREAD

**Issue by itsmohitanand** [SMARTlab-Purdue/Husformer#3]
https://github.com/SMARTlab-Purdue/Husformer/blob/4707d21d41fe0d6f03921a988df91252434cfcbf/src/3/models.py#L38

All of M3, M4 and M5 models create layers 
`self.proj1 = self.proj2 = nn.Linear(combined_dim, combined_dim)`  But is this layer ever used or called?
Can one safely remove them?

**Comment by zdz0086** [comment]
Yes, you could remove it. This is an optional linear layer before the output layer.
